<img width=150 src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/200px-NumPy_logo.svg.png"></img>

# Day 3 NumPy 陣列運算及數學 Universal Functions (ufunc)

NumPy 提供許多數學及統計的函式，這些函式的用法都很相似，針對陣列進行 element-wise 的操作，並回傳陣列做為輸出，稱為 Universal Functions (ufunc)。

在每個單元中常會介紹及用到不同的 ufunc，ufunc 的清單及文件可以參考官方連結：[Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)。

In [1]:
import numpy as np

## 1. 四則運算

陣列的加減乘除四則運算，可以使用運算子 (+, -, *, /) 或是呼叫函式來進行，語法及對照如下表：

|運算子|函式||
|---|---|---|
|a + b |np.add(a, b)|加法|
|a - b |np.substract(a, b)|減法|
|a * b |np.multiply(a, b)|乘法|
|a / b |np.divide(a, b)|除法|
|a % b |np.mod(a, b)|求餘數|

以上運算子的部分，使用與 Python 相同的運算子。

運算的時候，陣列的形狀 (shape) 必須相同，或是遵循廣播 (broadcasting) 規則，才能正確進行 element-wise 運算。規則如下：
- 兩個陣列形狀完全相同
- 比較兩個陣列的維度，如果維度的形狀相同的話，可以進行廣播
- 比較兩個陣列的維度，其中一個維度為1的話，可以進行廣播

有關於廣播的部分，會在後續線性代數的單元中有詳細說明及範例。

In [2]:
# 兩個純量相加
np.add(1.0, 3.0)

4.0

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 2, 2, 2])

In [4]:
a + b

array([3, 4, 5, 6, 7])

呼叫函式進行加法

In [5]:
np.add(a, b)

array([3, 4, 5, 6, 7])

In [6]:
a - b

array([-1,  0,  1,  2,  3])

In [7]:
a * b

array([ 2,  4,  6,  8, 10])

In [8]:
a / b

array([0.5, 1. , 1.5, 2. , 2.5])

In [9]:
a % b

array([1, 0, 1, 0, 1])

若是兩個陣列形狀不相同的話，遵循廣播規則，下面的例子可以正常運算。

In [10]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d = 3

In [12]:
c * d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

雖然 c 跟 e 的形狀不同，但是從各個維度的形狀比較後發現也是符合規則，還是可以進行運算。

In [13]:
e = np.random.randint(1, 10, 20).reshape(2, 10)
e

array([[4, 9, 9, 9, 6, 6, 8, 1, 2, 3],
       [3, 2, 7, 6, 8, 7, 8, 6, 2, 9]])

In [40]:
e.shape

(2, 10)

In [41]:
c.shape

(10,)

In [14]:
c + e

array([[ 4, 10, 11, 12, 10, 11, 14,  8, 10, 12],
       [ 3,  3,  9,  9, 12, 12, 14, 13, 10, 18]])

## 3. `sum()`

`sum()` 函式可以根據依指定的軸計算陣列元素值加總，基本語法如下：

```python
numpy.sum(a, axis=None, dtype=None, keepdims=<no value>)
```

In [15]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

若沒有指定軸的話，則是回傳所有元素加總值

In [16]:
a.sum()

45

語法使用 numpy.sum() 或是 a.sum() 都可以。

In [17]:
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

## 3. 次方 `np.power()`

次方的運算，跟四則運算一樣，也要遵循上述的規則，才能成功進行運算。語法如下表：

|運算子|函式|a 的 b 次方|
|---|---|---|
|a ** b |np.power(a, b)|$a^b$|

In [18]:
# 與 2**3 相同
np.power(2, 3)

8

In [19]:
# a 和 b 形狀相同
np.power(a, b)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [20]:
# e 和 c 的次方運算符合廣播規則
e ** c

array([[        1,         9,        81,       729,      1296,      7776,
           262144,         1,       256,     19683],
       [        1,         2,        49,       216,      4096,     16807,
           262144,    279936,       256, 387420489]])

## 4. 平方根 `np.sqrt()`

In [21]:
np.sqrt(4)

2.0

In [22]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

## 5. 歐拉數 (Euler's number) 及指數函式 `np.exp()`

NumPy 提供歐拉常數 $e$，以及指數函式 `np.exp()`，表示 $e^x$。

In [23]:
np.e

2.718281828459045

In [24]:
np.exp(1)

2.718281828459045

In [25]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 6. 對數函式

|函式||
|---|---|
|np.log(x)|底數為e|
|np.log2(x)|底數為2|
|np.log10(x)|底數為10|
|np.log1p(x)|底數為e，計算log(1+x)|

In [26]:
# 以 np.log10() 為例
np.log10(np.array([1, 10, 100, 1000, 10000]))

array([0., 1., 2., 3., 4.])

若要使用其他底數，可以用下列的方法 (以底數 3 為例)。

In [27]:
np.log(9)/np.log(3)

2.0

若是 log(負數) 則會產生 nan 常數，NaN / NAN 為 nan (not a number) 的別名。

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [29]:
np.log([-1, 1, 2])

array([       nan, 0.        , 0.69314718])

## 7. 取近似值

取近似值的函式及說明如下表：

|函式|常用語法|說明|
|---|---|---|
|round(), around()|ndarray.round(decimals=0)<br />numpy.round(a, decimals=0)<br />numpy.around(a, decimals=0)|在 Rounding 的方法部分，與 Python 同樣採用 IEEE 754 規範，<br />四捨、五取最近偶數、六入，而非我們一般講的四捨五入。<br /><br />round 與 around 用法及結果相同|
|rint()|numpy.rint(a)|Round至最近的整數|
|trunc()|numpy.trunc(a)|無條件捨去小數點|
|floor()|numpy.floor(a)|向下取整數|
|ceil()|numpy.ceil(a)|向上取整數|
|fix()|numpy.ceil(a)|向0的方向取整數|

In [30]:
a = np.array([1.65, 1.55, -3.57, 2.0])
a

array([ 1.65,  1.55, -3.57,  2.  ])

下面例子是進行小數點第二位的 rounding，從 a[0] 和 a[1] 的 rounding 結果可以看出 IEEE 754 的"四捨五取最近偶數六入"。

In [31]:
np.round(a, decimals=1)

array([ 1.6,  1.6, -3.6,  2. ])

`np.rint(a)` 與 `np.round(a, 0)` 的結果完全相同。

In [32]:
# Round至最近的整數
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [33]:
# 無條件捨去小數點
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [34]:
# 向下取整數
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [35]:
# 向上取整數
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [36]:
# 向0的方向取整數
np.fix(a)

array([ 1.,  1., -3.,  2.])

## 8. 取絕對值：`np.abs()`, `np.absolute()`, `np.fabs()`

`np.abs()` 是 `np.absolute()` 的簡寫，兩者完全相同；`np.fabs()` 的差異在於無法處理複數 (Complex)。

In [37]:
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [38]:
np.abs(a)

array([1.65, 1.55, 3.57, 2.  ])

如果傳入複數至 fabs() 的話則會產生錯誤。

In [39]:
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''