<img width=150 src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/200px-NumPy_logo.svg.png"></img>

# Day 7 NumPy 的矩陣函式與線性代數應用

In [2]:
import numpy as np

## 1. 矩陣乘積

## 1.1 點積 (dot product)：`numpy.dot(a, b)`

進行點積運算須注意形狀必須注意形狀 (shape)。若是兩個向量的點積，兩個向量的元素數目也須相同，或其中一個數目為 1 (廣播)。

若是兩個多維陣列 (矩陣) 的點積，則中間兩個大小要相同才能進行點積，例如：

$(2, 3) \cdot (3, 4) \to $ 成為 $(2, 4)$

點積的運算如下，假設 A 和 B：

$ A = 
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}
$

$ B =
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14}\\
b_{21} & b_{22} & b_{23} & b_{24}\\
b_{31} & b_{32} & b_{33} & b_{34}
\end{bmatrix}
$

兩個矩陣進行點積

![](img/dot_product.png)

In [2]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [3]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

如果形狀不符合則無法進行點積。

In [6]:
np.dot(np.arange(5), np.arange(3))

ValueError: shapes (5,) and (3,) not aligned: 5 (dim 0) != 3 (dim 0)

## 1.2 內積：`numpy.inner()`

一般來說內積是2個一維陣列(向量)做內積，公式如下：

$\vec a=[a_0, a_1, ..., a_{j-1}]$

$\vec b=[b_0, b_1, ..., b_{j-1}]$

$
\vec a \cdot \vec b=\sum a_0b_0+a_1b_1+...+a_{j-1}b_{j-1}
$

如果是多維陣列做乘積，那麼最後維度必須要符合，而內積結果就是其元素相乘之和。

In [7]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

In [8]:
a

array([5, 6, 8, 6, 1])

In [9]:
b

array([6, 4, 8, 1, 8])

In [10]:
np.inner(a, b)

132

## 1.3 外積：`numpy.outer()`

在線性代數中外積也稱為張量積。外積是2個一維陣列(向量)做計算，若非一維陣列的話會先進行展平(flatten)再進行外積。公式如下：

$\vec a=[a_0, a_1, ..., a_{i-1}]$

$\vec b=[b_0, b_1, ..., b_{j-1}]$

$\vec a \otimes \vec b =
\begin{bmatrix}
a_0b_0 & a_0b_1 & ... & a_0b_{j-1} \\
a_1b_0 & a_1b_1 & ... & a_1b_{j-1} \\
: & : & &: \\
: & : & &: \\
a_{i-1}b_0 & a_{i-1}b_1 & ... & a_{i-1}b_{j-1} \\
\end{bmatrix}
$

In [11]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [12]:
a

array([5, 6, 8, 6, 1])

In [13]:
b

array([6, 4, 8, 1, 8, 5])

In [14]:
np.outer(a, b)

array([[30, 20, 40,  5, 40, 25],
       [36, 24, 48,  6, 48, 30],
       [48, 32, 64,  8, 64, 40],
       [36, 24, 48,  6, 48, 30],
       [ 6,  4,  8,  1,  8,  5]])

## 1.4 矩陣乘法：`numpy.matmul()` 與 `@`

`matmul`與 `dot` 都是矩陣乘法 (Matrix Multiplication)，兩者非常類似，其相同及不同點如下：

* 如果2個都是二維陣列的話，`matmul`與 `dot` 相同。
* 在 `matmul` 中，多維的矩陣，將前 n-2 維視為後2维的元素後，進行乘法運算。
* `matmul` 不允許矩陣與純量相乘。

在 Python 3.5 版本之後提供 `@` 做為矩陣相乘運算子，在多個矩陣相乘時提供更簡潔的語法。

In [15]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

np.matmul(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [16]:
A @ B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

使用 `matmul` 進行矩陣與純量相乘時會產生錯誤。

In [17]:
np.matmul(A, 2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

## 2. 矩陣操作

In [18]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

array([[ 3,  0, -1],
       [ 2,  4,  1],
       [ 7,  2,  3]])

## 2.1 跡：`numpy.trace()`

$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$

$
trace(A) = a_{11} + a_{22} + a_{33}
$

跡的運算可以透過 `trace()` 函式求得：

In [19]:
np.trace(A)

10

## 2.2 行列式 (Determinant)：`numpy.linalg.det()`

$\vert A \vert= \begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}\\
= a_{11}\space a_{22}\space a_{33} + a_{12}\space a_{23}\space a_{31} + a_{13}\space a_{21}\space a_{32}
- a_{13}\space a_{22}\space a_{31} - a_{23}\space a_{32}\space a_{11} - a_{33}\space a_{12}\space a_{21}
$

圖解行列式運算 (Source: Wikipedia)
![](https://upload.wikimedia.org/wikipedia/commons/4/4d/Determinant-columns.png)

行列式的運算可以透過 `numpy.linalg.det()` 函式求得：

In [20]:
np.linalg.det(A)

53.999999999999986

若矩陣非方陣 (square)，則會產生錯誤

In [21]:
np.linalg.det(np.arange(6).reshape(3,2))

LinAlgError: Last 2 dimensions of the array must be square

## 2.3 反矩陣：`numpy.linalg.inv()`

以三階矩陣為例：

$
A = \left[\begin{array}{ccc|ccc}
a_{11} & a_{12} & a_{13} & 1 & 0 & 0\\
a_{21} & a_{22} & a_{23} & 0 & 1 & 0\\
a_{31} & a_{32} & a_{33} & 0 & 0 & 1
\end{array}\right]
$

透過高斯約當法 (Gaussian Elimination)，可以得到右邊的矩陣即為 A 的反矩陣

$
A^{-1} = \left[\begin{array}{ccc|ccc}
1 & 0 & 0 & b_{11} & b_{12} & b_{13} \\
0 & 1 & 0 & b_{21} & b_{22} & b_{23}\\
0 & 0 & 1 & b_{31} & b_{32} & b_{33}
\end{array}\right]
$

呼叫 `inv()` 函式可以得到反矩陣。

In [22]:
np.linalg.inv(A)

array([[ 0.18518519, -0.03703704,  0.07407407],
       [ 0.01851852,  0.2962963 , -0.09259259],
       [-0.44444444, -0.11111111,  0.22222222]])

若矩陣非方陣 (square)，則會產生錯誤

In [23]:
np.linalg.inv(np.arange(6).reshape(3,2))

LinAlgError: Last 2 dimensions of the array must be square

## 2.4 轉置 (Transpose)：`numpy.transpose()`

$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$

$
A^T = \begin{bmatrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{23} \\
a_{13} & a_{23} & a_{33}
\end{bmatrix}
$

轉置矩陣可透過呼叫 `numpy.transpose()` 函式達成。

In [24]:
np.transpose(A)

array([[ 3,  2,  7],
       [ 0,  4,  2],
       [-1,  1,  3]])

## 2.5 `numpy.linalg.eig()`

`eig()` 函式可以用來計算方陣的特徵值(eigenvalue)與特徵向量(eigenvector)。`eig()` 回傳值有2個：eigenvalue與eigenvector。

In [25]:
B = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])
B

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [26]:
w, v = np.linalg.eig(B)

In [27]:
# eigenvalues
w

array([-5.,  3.,  6.])

In [28]:
# eigenvectors
v

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

另外 `eigvals()` 函式也可以計算特徵值。

In [29]:
np.linalg.eigvals(B)

array([-5.,  3.,  6.])

## 2.6 秩：`numpy.linalg.matrix_rank()`

呼叫 `matrix_rank()` 回傳矩陣的秩(rank)，NumPy是使用SVD(奇異值分解；singular value decomposition)來計算秩。

In [30]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
np.linalg.matrix_rank(A)

3

## 2.7 `numpy.linalg.solve()`

求解線性系統可以使用 `solve()` 函式。

In [31]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

## 3. 特殊矩陣

## 3.1 單位矩陣：`numpy.identity()`

單位矩陣是對角線元素值為1的方陣。

In [32]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3.2 單位矩陣：`numpy.eye()`

`eye()` 也是用來產生對角線元素值為1的陣列，與 `identity()` 不同的地方在於 `eye()` 產生的可以不是方陣，也可以指定對角線開始的索引。

In [33]:
np.eye(5, 4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

可以從指定的Column索引開始。

In [34]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## 3.3 單對角陣列 (Diagonal)：`numpy.diagonal()` 與 `numpy.diag()`

`diagonal()` 與 `diag()` 語法基本上功能相同，差別在於 `diagonal()` 可以另行指定軸做為第一個軸或第二個軸。

In [4]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [37]:
np.diagonal(A, offset=1)

array([4, 6])

也可以使用 `array.diagonal()` 語法。

In [38]:
A.diagonal(offset=1)

array([4, 6])

要特別留意的是在不同版本的 NumPy 單對角陣列的回傳值有所不同。

> In versions of NumPy prior to 1.7, this function always returned a new, independent array containing a copy of the values in the diagonal.

> In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal, but depending on this fact is deprecated. Writing to the resulting array continues to work as it used to, but a FutureWarning is issued.

> Starting in NumPy 1.9 it returns a read-only view on the original array. Attempting to write to the resulting array will produce an error.

若要覆寫回傳的陣列，建議使用 `np.diagonal(a).copy()` 會是各版本相容性最高的語法。

## 3.4 三角矩陣：`numpy.tri()`

`tri()` 可以用來產生對角線以下都是1的元素，下面的例子是產生形狀(3,5)的陣列，從Column索引1開始的對角線以下元素值均為1。

In [35]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

## 3.5 上三角矩陣 (Upper Triangular)、下三角矩陣 (Lower Triangular)：`numpy.triu()`、`numpy.tril()`

`triu()`、`numpy.tril()` 可將對角線以上或以下的元素值設為0，也可以指定對角線起始的索引。

In [39]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [40]:
np.triu(A)

array([[3, 4, 0],
       [0, 4, 6],
       [0, 0, 5]])

In [41]:
np.tril(A, 1)

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

## 4. 矩陣分解 (Matrix Decomposition)

NumPy 線性代數函式中提供3種矩陣分解的函式：
* Cholskey Decomposition
* QR Factorization
* Singular Value Decomposition (SVD)

In [42]:
B = np.array([[1, 2],[2, 50]])
B

array([[ 1,  2],
       [ 2, 50]])

## 4.1 `numpy.linalg.cholesky()`

In [5]:
B = np.array([[1, 2],[2, 50]])
B

array([[ 1,  2],
       [ 2, 50]])

In [6]:
np.linalg.cholesky(B)

array([[1.        , 0.        ],
       [2.        , 6.78232998]])

## 4.2 `numpy.linalg.qr()`

In [44]:
q, r = np.linalg.qr(B)

In [45]:
q

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [46]:
r

array([[ -2.23606798, -45.61578674],
       [  0.        ,  20.57182539]])

## 4.3 `numpy.linalg.svd()`

In [47]:
u, s, vh = np.linalg.svd(B)

In [48]:
u

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])

In [49]:
s

array([50.08149711,  0.91850289])

In [50]:
vh

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])